/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package De4_2;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author An Nguyen Van
 */
public class ThemMoiMatHang extends javax.swing.JFrame {

    /**
     * Creates new form ThemMoiMatHang
     */
    public ThemMoiMatHang() {
        initComponents();
        setLocationRelativeTo(null);
        
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(jbrTrangSuc);
        buttonGroup.add(jbrTienTe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHangThemMoi = new javax.swing.JTextField();
        txtTenHangThemMoi = new javax.swing.JTextField();
        txtDuocPhepMuaBanThemMoi = new javax.swing.JTextField();
        jbrTrangSuc = new javax.swing.JRadioButton();
        jbrTienTe = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtGiaTheoCanThemMoi = new javax.swing.JTextField();
        txtTyGiaChuyenDoiThemMoi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThemMoi = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THEM MOI MAT HANG");

        jLabel2.setText("Ma Hang");

        jLabel3.setText("Ten Hang");

        jLabel4.setText("Duoc Phep Mua Ban Khong?");

        jbrTrangSuc.setText("Trang Suc");
        jbrTrangSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrTrangSucActionPerformed(evt);
            }
        });

        jbrTienTe.setText("Tien Te");
        jbrTienTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrTienTeActionPerformed(evt);
            }
        });

        jLabel6.setText("Gia Theo Can");

        jLabel7.setText("Ty Gia Chuyen Doi");

        btnThemMoi.setText("Them Moi");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnDong.setText("Dong");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDuocPhepMuaBanThemMoi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaHangThemMoi)
                                    .addComponent(txtTenHangThemMoi))))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbrTrangSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTheoCanThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTyGiaChuyenDoiThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbrTienTe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThemMoi)
                        .addGap(32, 32, 32)
                        .addComponent(btnDong)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHangThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbrTrangSuc)
                    .addComponent(jbrTienTe))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenHangThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaTheoCanThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTyGiaChuyenDoiThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDuocPhepMuaBanThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi)
                    .addComponent(btnDong))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        try{
            ArrayList<String> maHangCoSan = new ArrayList<>();
            
            Scanner sc = new Scanner(new File("mathangDe4_2.txt"));
            while(sc.hasNext()){
                String line = sc.nextLine();
                
                String[] parts = line.split("\\$");
                
                maHangCoSan.add(parts[1]);
            }
            
            FileWriter fw = new FileWriter("mathangDe4_2.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);
            
            if(jbrTrangSuc.isSelected()){
                txtTyGiaChuyenDoiThemMoi.hide();
                
                TrangSuc ts = new TrangSuc();
                ts.setMaHang(txtMaHangThemMoi.getText());
                ts.setTenHang(txtTenHangThemMoi.getText());
                ts.setDuocPhepMuaBan(Boolean.parseBoolean(txtDuocPhepMuaBanThemMoi.getText()));
                ts.setGiaTheoCan(Double.parseDouble(txtGiaTheoCanThemMoi.getText()));
                
                for(int i=0; i<maHangCoSan.size(); i++){
                    if(maHangCoSan.get(i).equals(ts.getMaHang())){
                        JOptionPane.showMessageDialog(rootPane, "Ma Hang Da Ton Tai! Vui Long Thu Lai.");
                        return;
                    }
                }
                
                bw.write("TrangSuc$" + ts.getMaHang() + "$" + ts.getTenHang() + "$" + ts.isDuocPhepMuaBan()+ "$" + ts.getGiaTheoCan());
                bw.newLine();
                JOptionPane.showMessageDialog(rootPane, "Them Mat Hang Trang Suc Moi Thanh Cong!");
            }
            else if(jbrTienTe.isSelected()){
                txtGiaTheoCanThemMoi.hide();
                
                TienTe tt = new TienTe();
                tt.setMaHang(txtMaHangThemMoi.getText());
                tt.setTenHang(txtTenHangThemMoi.getText());
                tt.setDuocPhepMuaBan(Boolean.parseBoolean(txtDuocPhepMuaBanThemMoi.getText()));
                tt.setTiGiaChuyenDoi(Double.parseDouble(txtTyGiaChuyenDoiThemMoi.getText()));
                
                for(int i=0; i<maHangCoSan.size(); i++){
                    if(maHangCoSan.get(i).equals(tt.getMaHang())){
                        JOptionPane.showMessageDialog(rootPane, "Ma Hang Da Ton Tai! Vui Long Thu Lai.");
                        return;
                    }
                }
                
                bw.write("TienTe$" + tt.getMaHang() + "$" + tt.getTenHang() + "$" + tt.isDuocPhepMuaBan()+ "$" + tt.getTiGiaChuyenDoi());
                bw.newLine();
                JOptionPane.showMessageDialog(rootPane, "Them Mat Hang Tien Te Moi Thanh Cong!");
            }
            bw.close();
        }catch(IOException e){
            System.out.println("Loi Khi Mo File!" + e.getMessage());
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void jbrTrangSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrTrangSucActionPerformed
        // TODO add your handling code here:
        txtTyGiaChuyenDoiThemMoi.setEditable(false);
        txtGiaTheoCanThemMoi.setEditable(true);
    }//GEN-LAST:event_jbrTrangSucActionPerformed

    private void jbrTienTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrTienTeActionPerformed
        // TODO add your handling code here:
        txtGiaTheoCanThemMoi.setEditable(false);
        txtTyGiaChuyenDoiThemMoi.setEditable(true);
    }//GEN-LAST:event_jbrTienTeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMoiMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMoiMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMoiMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMoiMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMoiMatHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jbrTienTe;
    private javax.swing.JRadioButton jbrTrangSuc;
    private javax.swing.JTextField txtDuocPhepMuaBanThemMoi;
    private javax.swing.JTextField txtGiaTheoCanThemMoi;
    private javax.swing.JTextField txtMaHangThemMoi;
    private javax.swing.JTextField txtTenHangThemMoi;
    private javax.swing.JTextField txtTyGiaChuyenDoiThemMoi;
    // End of variables declaration//GEN-END:variables
}
