/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package De1_2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author An Nguyen Van
 */
public class ThemMoiNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form ThemMoiNhanVien
     */
    
    private ButtonGroup loaiNhanVien;
    private ButtonGroup coPhaiBepTruong;
    private ButtonGroup coBietNgoaiNgu;
    private DefaultTableModel tableModel;
    
    private ArrayList<NhanVien> danhSachNhanVien;
    
    public ThemMoiNhanVien() {
        initComponents();
        setLocationRelativeTo(null);
        
        loaiNhanVien = new ButtonGroup();
        loaiNhanVien.add(rbNhanVienBep);
        loaiNhanVien.add(rbNhanVienThuNgan);
        
        coPhaiBepTruong = new ButtonGroup();
        coPhaiBepTruong.add(rbNhanVienBepCo);
        coPhaiBepTruong.add(rbNhanVienBepKhong);
        
        coBietNgoaiNgu = new ButtonGroup();
        coBietNgoaiNgu.add(rbNhanVienThuNganCo);
        coBietNgoaiNgu.add(rbNhanVienThuNganKhong);
        
        danhSachNhanVien = new ArrayList<>();
        tableModel = (DefaultTableModel) tbNhanVien.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtThamNien = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtSoGioLamViec = new javax.swing.JTextField();
        txtLuongGio = new javax.swing.JTextField();
        rbNhanVienBep = new javax.swing.JRadioButton();
        rbNhanVienThuNgan = new javax.swing.JRadioButton();
        rbNhanVienBepCo = new javax.swing.JRadioButton();
        lbNhanVienBep1 = new javax.swing.JLabel();
        rbNhanVienBepKhong = new javax.swing.JRadioButton();
        lbNhanVienBep2 = new javax.swing.JLabel();
        txtThuongChucVu = new javax.swing.JTextField();
        lbNhanVienThuNgan = new javax.swing.JLabel();
        rbNhanVienThuNganCo = new javax.swing.JRadioButton();
        rbNhanVienThuNganKhong = new javax.swing.JRadioButton();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THEM MOI NHAN VIEN BEP, NHAN VIEN THU NGAN");

        jLabel2.setText("Ho Ten:");

        jLabel3.setText("Tham Nien");

        jLabel4.setText("Que Quan:");

        jLabel5.setText("So Gio Lam Viec");

        jLabel6.setText("Luong Gio:");

        txtLuongGio.setEditable(false);
        txtLuongGio.setText("100.000");

        rbNhanVienBep.setText("Nhan Vien Bep");
        rbNhanVienBep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanVienBepActionPerformed(evt);
            }
        });

        rbNhanVienThuNgan.setText("Nhan Vien Thu Ngan");
        rbNhanVienThuNgan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhanVienThuNganActionPerformed(evt);
            }
        });

        rbNhanVienBepCo.setText("Co");

        lbNhanVienBep1.setText("Co Phai Bep Truong Khong?");
        lbNhanVienBep1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                lbNhanVienBep1ComponentMoved(evt);
            }
        });

        rbNhanVienBepKhong.setText("Khong");

        lbNhanVienBep2.setText("Thuong Chuc Vu (10%):");

        lbNhanVienThuNgan.setText("Co Biet Ngoai Ngu Khong?");

        rbNhanVienThuNganCo.setText("Co");

        rbNhanVienThuNganKhong.setText("Khong");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnDong.setText("Dong");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnLuuFile.setText("Luu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        btnHienThi.setText("Hien Thi");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ho Ten", "Tham Nien", "Que Quan", "So Gio Lam Viec", "Luong Gio", "Co Phai Bep Truong", "Thuong Chuc Vu (BT)", "Co Biet Ngoai Ngu", "Luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLuongGio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoGioLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbNhanVienBep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbNhanVienBep, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(lbNhanVienBep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtThuongChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbNhanVienBepCo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbNhanVienBepKhong, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbNhanVienThuNgan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbNhanVienThuNganCo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbNhanVienThuNganKhong, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(rbNhanVienThuNgan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLuu)
                                .addGap(30, 30, 30)
                                .addComponent(btnLuuFile)
                                .addGap(30, 30, 30)
                                .addComponent(btnHienThi)
                                .addGap(30, 30, 30)
                                .addComponent(btnDong)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbNhanVienBep)
                    .addComponent(rbNhanVienThuNgan))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtThamNien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbNhanVienBepCo)
                    .addComponent(lbNhanVienBep1)
                    .addComponent(rbNhanVienBepKhong)
                    .addComponent(lbNhanVienThuNgan)
                    .addComponent(rbNhanVienThuNganCo)
                    .addComponent(rbNhanVienThuNganKhong))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNhanVienBep2)
                    .addComponent(txtThuongChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoGioLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLuongGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu)
                    .addComponent(btnDong)
                    .addComponent(btnLuuFile)
                    .addComponent(btnHienThi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void resetForm(){
        txtHoTen.setText("");
        txtThamNien.setText("");
        txtQueQuan.setText("");
        txtSoGioLamViec.setText("");
        loaiNhanVien.clearSelection();
        coBietNgoaiNgu.clearSelection();
        coPhaiBepTruong.clearSelection();
        txtThuongChucVu.setText("");
    }
    
    private void lbNhanVienBep1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbNhanVienBep1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNhanVienBep1ComponentMoved

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(rbNhanVienBep.isSelected()){
            NhanVienBep nvb = new NhanVienBep();
            
            nvb.setHoTen(txtHoTen.getText());
            nvb.setThamNien(Integer.parseInt(txtThamNien.getText()));
            nvb.setQueQuan(txtQueQuan.getText());
            nvb.setSoGioLamViec(Float.parseFloat(txtSoGioLamViec.getText()));
            if(rbNhanVienBepKhong.isSelected()){
                nvb.setIsBepTruong(false);
                nvb.setThuongChucVu(0);
                txtThuongChucVu.setEditable(false);
            }
            else if(rbNhanVienBepCo.isSelected()){
                nvb.setIsBepTruong(true);
                txtThuongChucVu.setEditable(true);
                nvb.setThuongChucVu(Integer.parseInt(txtThuongChucVu.getText()));
            }
            danhSachNhanVien.add(nvb);
            JOptionPane.showMessageDialog(rootPane, "Them Nhan Vien Bep Thanh Cong!");
            resetForm();
        }
        else if(rbNhanVienThuNgan.isSelected()){
            NhanVienThuNgan nvtn = new NhanVienThuNgan();
            
            nvtn.setHoTen(txtHoTen.getText());
            nvtn.setThamNien(Integer.parseInt(txtThamNien.getText()));
            nvtn.setQueQuan(txtQueQuan.getText());
            nvtn.setSoGioLamViec(Float.parseFloat(txtSoGioLamViec.getText()));
            if(rbNhanVienThuNganCo.isSelected()){
                nvtn.setIsBietNgoaiNgu(true);
            }
            else if(rbNhanVienThuNganKhong.isSelected()){
                nvtn.setIsBietNgoaiNgu(false);
            }
            nvtn.tinhLuong();
            danhSachNhanVien.add(nvtn);
            JOptionPane.showMessageDialog(rootPane, "Them Nhan Vien Thu Ngan Thanh Cong!");
            resetForm();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ban Chua Chon Chuc Vu!");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void rbNhanVienBepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanVienBepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNhanVienBepActionPerformed

    private void rbNhanVienThuNganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhanVienThuNganActionPerformed
        // TODO add your handling code here:
        txtThuongChucVu.setEditable(false);
    }//GEN-LAST:event_rbNhanVienThuNganActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("nhanvienDe1_2.txt");
            
            PrintWriter pw = new PrintWriter(file);
            if(danhSachNhanVien.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Danh Sach Nhan Vien Trong!");
                return;
            }
            for(NhanVien nv : danhSachNhanVien){
                pw.println(nv.toString());
            }
            pw.close();
            JOptionPane.showMessageDialog(rootPane, "Ghi File Thanh Cong!");
        }catch(FileNotFoundException e){
            System.out.println("Loi Khi Mo File" + e.getMessage());
        }
    }//GEN-LAST:event_btnLuuFileActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        for(NhanVien nv : danhSachNhanVien){
            if(nv instanceof NhanVienBep nvb){
                Object[] row = new Object[]{
                    nvb.getHoTen(), nvb.getThamNien(), nvb.getQueQuan(), nvb.getSoGioLamViec(), nvb.LUONG_GIO
                        , nvb.isIsBepTruong(), nvb.getThuongChucVu(), null, nvb.tinhLuong()
                };
                tableModel.addRow(row);
                tableModel.fireTableDataChanged();
            }
            else if(nv instanceof NhanVienThuNgan nvtn){
                Object[] row = new Object[]{
                    nvtn.getHoTen(), nvtn.getThamNien(), nvtn.getQueQuan(), nvtn.getSoGioLamViec(), nvtn.LUONG_GIO
                        ,null, null, nvtn.isIsBietNgoaiNgu(), nvtn.tinhLuong()
                };
                tableModel.addRow(row);
                tableModel.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_btnHienThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMoiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMoiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMoiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMoiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMoiNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNhanVienBep1;
    private javax.swing.JLabel lbNhanVienBep2;
    private javax.swing.JLabel lbNhanVienThuNgan;
    private javax.swing.JRadioButton rbNhanVienBep;
    private javax.swing.JRadioButton rbNhanVienBepCo;
    private javax.swing.JRadioButton rbNhanVienBepKhong;
    private javax.swing.JRadioButton rbNhanVienThuNgan;
    private javax.swing.JRadioButton rbNhanVienThuNganCo;
    private javax.swing.JRadioButton rbNhanVienThuNganKhong;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuongGio;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSoGioLamViec;
    private javax.swing.JTextField txtThamNien;
    private javax.swing.JTextField txtThuongChucVu;
    // End of variables declaration//GEN-END:variables
}
