/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package De1_1;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author An Nguyen Van
 */
public class ThemMoiCanBo extends javax.swing.JFrame {

    /**
     * Creates new form ThemMoiCanBo
     */
    
    private ArrayList<CanBo> danhSachCanBo;
    private DefaultTableModel tableModel;
    private ButtonGroup buttonGroup;

    public ThemMoiCanBo() {
        initComponents();
        setLocationRelativeTo(null);
        danhSachCanBo = new ArrayList<>();
        tableModel = (DefaultTableModel) tblCanBo.getModel();
        
        buttonGroup = new ButtonGroup();
        buttonGroup.add(jbrNhanVien);
        buttonGroup.add(jbrQuanLy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNamSinh = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtHeSoLuong = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jbrNhanVien = new javax.swing.JRadioButton();
        jbrQuanLy = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtNganhDaoTao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHeSoChucVu = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        btnLuuFile = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCanBo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THEM MOI NHAN VIEN, QUAN LY");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ho Ten: ");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nam Sinh");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gioi Tinh:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dia Chi:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("He So Luong:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LUONG CO BAN:");

        jTextField6.setEditable(false);
        jTextField6.setText("2.000.000");

        jbrNhanVien.setText("Nhan Vien");
        jbrNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrNhanVienActionPerformed(evt);
            }
        });

        jbrQuanLy.setText("Quan Ly");
        jbrQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrQuanLyActionPerformed(evt);
            }
        });

        jLabel8.setText("Nganh Dao Tao:");

        jLabel9.setText("He So Chuc Vu (<1):");

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu" }));
        cbbGioiTinh.setSelectedIndex(-1);

        btnLuuFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuFile.setText("Luu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        btnHienThi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHienThi.setText("Hien Thi");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        tblCanBo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ho Ten", "Nam Sinh", "Gioi Tinh", "Dia Chi", "He So Luong", "Luong Co Ban", "Thong Tin Them", "Tinh Luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCanBo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(67, 67, 67)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jbrNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btnLuu))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(btnLuuFile)
                                                            .addComponent(txtNganhDaoTao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jbrQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtHeSoChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnHienThi)
                                                .addGap(177, 177, 177))))
                                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbrNhanVien)
                    .addComponent(jbrQuanLy))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNganhDaoTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtHeSoChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu)
                    .addComponent(btnLuuFile)
                    .addComponent(btnHienThi))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbrNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrNhanVienActionPerformed
        // TODO add your handling code here:
        if(jbrNhanVien.isSelected()){
            txtHeSoChucVu.setEditable(false);
            txtNganhDaoTao.setEditable(true);
        }
    }//GEN-LAST:event_jbrNhanVienActionPerformed

    private void jbrQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrQuanLyActionPerformed
        // TODO add your handling code here:
        if(jbrQuanLy.isSelected()){
            txtNganhDaoTao.setEditable(false);
            txtHeSoChucVu.setEditable(true);
        }
    }//GEN-LAST:event_jbrQuanLyActionPerformed

    public void resetForm(){
        txtHoTen.setText("");
        txtNamSinh.setText("");
        txtDiaChi.setText("");
        txtHeSoLuong.setText("");
        txtNganhDaoTao.setText("");
        txtHeSoChucVu.setText("");
        cbbGioiTinh.setSelectedIndex(-1);
        buttonGroup.clearSelection();
    }
    
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(jbrNhanVien.isSelected()){
            NhanVien nv = new NhanVien();
            
            nv.setHoTen(txtHoTen.getText());
            if(Double.parseDouble(txtNamSinh.getText()) > 2025 || Double.parseDouble(txtNamSinh.getText()) < 1900){
                JOptionPane.showMessageDialog(rootPane, "Nam Sinh Khong Hop Le! Vui Long Thu Lai");
                return;
            }
            nv.setNamSinh(txtNamSinh.getText());
            nv.setGioiTinh(cbbGioiTinh.getSelectedItem().toString());
            nv.setDiaChi(txtDiaChi.getText());
            nv.setHeSoLuong(Double.parseDouble(txtHeSoLuong.getText()));
            nv.setNganhDaoTao(txtNganhDaoTao.getText());
            
            danhSachCanBo.add(nv);
            JOptionPane.showMessageDialog(rootPane, "Them Nhan Vien Thanh Cong!");
            resetForm();
        }
        else if(jbrQuanLy.isSelected()){
            QuanLy ql = new QuanLy();
            
            ql.setHoTen(txtHoTen.getText());
            if(Double.parseDouble(txtNamSinh.getText()) > 2025 || Double.parseDouble(txtNamSinh.getText()) < 1900){
                JOptionPane.showMessageDialog(rootPane, "Nam Sinh Khong Hop Le! Vui Long Thu Lai");
                return;
            }
            ql.setNamSinh(txtNamSinh.getText());
            ql.setGioiTinh(cbbGioiTinh.getSelectedItem().toString());
            ql.setDiaChi(txtDiaChi.getText());
            ql.setHeSoLuong(Double.parseDouble(txtHeSoLuong.getText()));
            if(Double.parseDouble(txtHeSoChucVu.getText()) > 1 || Double.parseDouble(txtHeSoChucVu.getText()) < 0){
                JOptionPane.showMessageDialog(rootPane, "He So Chuc Vu Khong Hop Le! Vui Long Thu Lai");
                return;
            }
            ql.setHeSoChucVu(Double.parseDouble(txtHeSoChucVu.getText()));
            
            danhSachCanBo.add(ql);
            JOptionPane.showMessageDialog(rootPane, "Them Quan Ly Thanh cong!");
            resetForm();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("canboDe1_1.txt");
            
            PrintWriter pw = new PrintWriter(file);
            
            if(danhSachCanBo.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Danh Sach Can Bo Trong! Khong The Luu File");
                return;
            }
            
            for(CanBo cb : danhSachCanBo){
                pw.println(cb.toString());
            }
            pw.close();
            JOptionPane.showMessageDialog(rootPane, "Luu File Thanh Cong!");
        }catch(FileNotFoundException e){
            System.out.println("Loi Khi Mo File!" + e.getMessage());
        }
    }//GEN-LAST:event_btnLuuFileActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        for(CanBo cb : danhSachCanBo){
            if(cb instanceof NhanVien nv){
                Object[] row = new Object[]{
                    nv.getHoTen(), nv.getNamSinh(), nv.getGioiTinh(), nv.getDiaChi(), nv.getHeSoLuong(), nv.LUONG_CO_BAN, "NganhDaoTao: " + nv.getNganhDaoTao(), nv.tinhLuong()
                };
                tableModel.addRow(row);
                tableModel.fireTableDataChanged();
            }
            else if(cb instanceof QuanLy ql){
                Object[] row = new Object[]{
                    ql.getHoTen(), ql.getNamSinh(), ql.getGioiTinh(), ql.getDiaChi(), ql.getHeSoLuong(), ql.LUONG_CO_BAN, "HeSoChucVu:" + ql.getHeSoChucVu(), ql.tinhLuong()
                };
                tableModel.addRow(row);
                tableModel.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_btnHienThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMoiCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMoiCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMoiCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMoiCanBo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMoiCanBo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JRadioButton jbrNhanVien;
    private javax.swing.JRadioButton jbrQuanLy;
    private javax.swing.JTable tblCanBo;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHeSoChucVu;
    private javax.swing.JTextField txtHeSoLuong;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtNganhDaoTao;
    // End of variables declaration//GEN-END:variables
}
