/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package De3_1;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author An Nguyen Van
 */
public class ThemMoiThiSinh extends javax.swing.JFrame {

    /**
     * Creates new form ThemMoiThiSinh
     */
    
    private ArrayList<ThiSinh> danhSachThiSinh;
    private ButtonGroup groupThiSinh;
    private DefaultTableModel tableModel;
    
    public ThemMoiThiSinh() {
        initComponents();
        setLocationRelativeTo(null);
        danhSachThiSinh = new ArrayList<>();
        groupThiSinh = new ButtonGroup();
        groupThiSinh.add(rbKhoiA);
        groupThiSinh.add(rbKhoiD);
        tableModel = (DefaultTableModel) tableThiSinh.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbKhoiA = new javax.swing.JRadioButton();
        rbKhoiD = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        txtHoTen = new javax.swing.JTextField();
        txtSoBaoDanh = new javax.swing.JTextField();
        txtTruongHoc = new javax.swing.JTextField();
        txtDiemCong = new javax.swing.JTextField();
        txtDiemSan = new javax.swing.JTextField();
        txtDiemToanA = new javax.swing.JTextField();
        txtDiemLyA = new javax.swing.JTextField();
        txtDiemHoaA = new javax.swing.JTextField();
        txtDiemToanD = new javax.swing.JTextField();
        txtDiemVanD = new javax.swing.JTextField();
        txtDiemAnhD = new javax.swing.JTextField();
        btnLuuFile = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThiSinh = new javax.swing.JTable();
        btnThiSinhKhoiD = new javax.swing.JButton();
        btnCoDiemTren8 = new javax.swing.JButton();
        btnThapHonDiemSan = new javax.swing.JButton();
        btnThiSinhKhoiA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THEM MOI THI SINH");

        jLabel2.setText("DIEM SAN");

        jLabel3.setText("Ho Ten:");

        jLabel4.setText("So Bao Danh:");

        jLabel5.setText("Truong Hoc:");

        jLabel6.setText("Diem Cong:");

        jLabel7.setText("Diem Toan");

        rbKhoiA.setText("Thi Sinh Khoi A");

        rbKhoiD.setText("Thi Sinh Khoi D");

        jLabel8.setText("Diem Ly");

        jLabel9.setText("Diem Hoa");

        jLabel10.setText("Diem Toan");

        jLabel11.setText("Diem Van");

        jLabel12.setText("Diem Anh");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        txtDiemSan.setEditable(false);
        txtDiemSan.setText("3");

        btnLuuFile.setText("Luu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BANG THONG KE");

        tableThiSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ho Ten", "So Bao Danh", "Truong Hoc", "Diem Cong", "Diem San", "Loai Thi Sinh", "Diem Mon 1", "Diem Mon 2", "Diem Mon 3", "Tong Diem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableThiSinh);

        btnThiSinhKhoiD.setText("Thong Ke Thi Sinh Khoi D");
        btnThiSinhKhoiD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThiSinhKhoiDActionPerformed(evt);
            }
        });

        btnCoDiemTren8.setText("Thi Sinh Co Diem Tren 8");
        btnCoDiemTren8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoDiemTren8ActionPerformed(evt);
            }
        });

        btnThapHonDiemSan.setText("Thi Sinh Thap Hon Diem San");
        btnThapHonDiemSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThapHonDiemSanActionPerformed(evt);
            }
        });

        btnThiSinhKhoiA.setText("Thong Ke Thi Sinh Khoi A");
        btnThiSinhKhoiA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThiSinhKhoiAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThiSinhKhoiA)
                            .addGap(20, 20, 20)
                            .addComponent(btnThiSinhKhoiD)
                            .addGap(20, 20, 20)
                            .addComponent(btnCoDiemTren8)
                            .addGap(20, 20, 20)
                            .addComponent(btnThapHonDiemSan))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSoBaoDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTruongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDiemCong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDiemSan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(54, 54, 54)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(98, 98, 98)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbKhoiA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLuu))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDiemToanA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDiemLyA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDiemHoaA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(45, 45, 45)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbKhoiD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(35, 35, 35)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtDiemAnhD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtDiemVanD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtDiemToanD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(btnLuuFile)))
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbKhoiA)
                        .addComponent(rbKhoiD)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(txtSoBaoDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemToanA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemToanD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(txtTruongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemLyA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemVanD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(txtDiemCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemHoaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemAnhD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDiemSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu)
                    .addComponent(btnLuuFile))
                .addGap(63, 63, 63)
                .addComponent(jLabel13)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThiSinhKhoiD)
                    .addComponent(btnCoDiemTren8)
                    .addComponent(btnThapHonDiemSan)
                    .addComponent(btnThiSinhKhoiA))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void resetForm(){
        txtHoTen.setText("");
        txtSoBaoDanh.setText("");
        txtTruongHoc.setText("");
        txtDiemCong.setText("");
        txtDiemToanA.setText("");
        txtDiemLyA.setText("");
        txtDiemHoaA.setText("");
        txtDiemToanD.setText("");
        txtDiemVanD.setText("");
        txtDiemAnhD.setText("");
        groupThiSinh.clearSelection();
    }
    
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:        
        if(rbKhoiA.isSelected()){
            ThiSinhKhoiA tsA = new ThiSinhKhoiA();
            
            tsA.setHoTen(txtHoTen.getText());
            tsA.setSoBaoDanh(txtSoBaoDanh.getText());
            tsA.setTruongHoc(txtTruongHoc.getText());
            tsA.setDiemCong(Double.parseDouble(txtDiemCong.getText()));
            tsA.setDiemToan(Double.parseDouble(txtDiemToanA.getText()));
            tsA.setDiemLy(Double.parseDouble(txtDiemLyA.getText()));
            tsA.setDiemHoa(Double.parseDouble(txtDiemHoaA.getText()));
            
            danhSachThiSinh.add(tsA);
            JOptionPane.showMessageDialog(rootPane, "Them Thi Sinh Khoi A Thanh Cong!");
            resetForm();
        }
        else if(rbKhoiD.isSelected()){
            ThiSinhKhoiD tsD = new ThiSinhKhoiD();
            
            tsD.setHoTen(txtHoTen.getText());
            tsD.setSoBaoDanh(txtSoBaoDanh.getText());
            tsD.setTruongHoc(txtTruongHoc.getText());
            tsD.setDiemCong(Double.parseDouble(txtDiemCong.getText()));
            tsD.setDiemToan(Double.parseDouble(txtDiemToanD.getText()));
            tsD.setDiemVan(Double.parseDouble(txtDiemVanD.getText()));
            tsD.setDiemAnh(Double.parseDouble(txtDiemAnhD.getText()));
            
            danhSachThiSinh.add(tsD);
            JOptionPane.showMessageDialog(rootPane, "Them Thi Sinh Khoi D Thanh Cong!");
            resetForm();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Vui Long Chon Loai Thi Sinh!");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("thisinhDe3_1.txt");
            
            PrintWriter pw = new PrintWriter(file);
            if(danhSachThiSinh.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Danh Sach Thi Sinh Trong!");
                return;
            }
            for(ThiSinh ts : danhSachThiSinh){
                pw.println(ts.toString());
            }
            pw.close();
            JOptionPane.showMessageDialog(rootPane, "Ghi File Thanh Cong!");
        }
        catch(FileNotFoundException e){
            System.out.println("Loi Khi Mo File" + e.getMessage());
        }
    }//GEN-LAST:event_btnLuuFileActionPerformed
    
    public void xoaDuLieuCu(){
        tableModel.setRowCount(0);
    }
    
    private void btnThiSinhKhoiDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThiSinhKhoiDActionPerformed
        // TODO add your handling code here:
        xoaDuLieuCu();
        
        boolean isChecked = false;
        int count = 0;
        
        for(ThiSinh ts : danhSachThiSinh){
            if(ts instanceof ThiSinhKhoiD){
                isChecked = true;
                ++count;
                Object[] row = new Object[]{
                    ts.getHoTen(), ts.getSoBaoDanh(), ts.getTruongHoc(), ts.getDiemCong(), ((ThiSinhKhoiD) ts).DIEM_SAN, "Khoi D", ((ThiSinhKhoiD) ts).getDiemToan(), 
                    ((ThiSinhKhoiD) ts).getDiemVan(), ((ThiSinhKhoiD) ts).getDiemAnh(), ((ThiSinhKhoiD) ts).tinhDiem()
                };
                tableModel.addRow(row);
            }
        }
        tableModel.fireTableDataChanged();
        if(isChecked == false){
            JOptionPane.showMessageDialog(rootPane, "Khong Co Thi Sinh Khoi D!");
        }
        if(count != 0){
            JOptionPane.showMessageDialog(rootPane, "Co " + count + " Thi Sinh Khoi D!");
        }
    }//GEN-LAST:event_btnThiSinhKhoiDActionPerformed

    private void btnThiSinhKhoiAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThiSinhKhoiAActionPerformed
        // TODO add your handling code here:
        xoaDuLieuCu();

        boolean isChecked = false;
        int count = 0;
        
        for(ThiSinh ts : danhSachThiSinh){
            if(ts instanceof ThiSinhKhoiA){
                isChecked = true;
                ++count;
                Object[] row = new Object[]{
                    ts.getHoTen(), ts.getSoBaoDanh(), ts.getTruongHoc(), ts.getDiemCong(), ((ThiSinhKhoiA) ts).DIEM_SAN, "Khoi A", ((ThiSinhKhoiA) ts).getDiemToan(), 
                    ((ThiSinhKhoiA) ts).getDiemLy(), ((ThiSinhKhoiA) ts).getDiemHoa(), ((ThiSinhKhoiA) ts).tinhDiem()
                };
                tableModel.addRow(row);
            }
        }
        tableModel.fireTableDataChanged();
        if(isChecked == false){
            JOptionPane.showMessageDialog(rootPane, "Khong Co Thi Sinh Khoi A!");
        }
        if(count != 0){
            JOptionPane.showMessageDialog(rootPane, "Co " + count + " Thi Sinh Khoi A!");
        }
    }//GEN-LAST:event_btnThiSinhKhoiAActionPerformed

    private void btnCoDiemTren8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoDiemTren8ActionPerformed
        // TODO add your handling code here:
        xoaDuLieuCu();
        
        boolean isChecked = false;
        int count = 0;
        
        for(ThiSinh ts : danhSachThiSinh){
            if(ts instanceof ThiSinhKhoiA){
                if(((ThiSinhKhoiA) ts).tinhDiem() > 8){
                    isChecked = true;
                    ++count;
                    Object[] row = new Object[]{
                        ts.getHoTen(), ts.getSoBaoDanh(), ts.getTruongHoc(), ts.getDiemCong(), ((ThiSinhKhoiA) ts).DIEM_SAN, "Khoi A", ((ThiSinhKhoiA) ts).getDiemToan(), 
                        ((ThiSinhKhoiA) ts).getDiemLy(), ((ThiSinhKhoiA) ts).getDiemHoa(), ((ThiSinhKhoiA) ts).tinhDiem()
                    };
                    tableModel.addRow(row);
                }
            }
            else if(ts instanceof ThiSinhKhoiD){
                if(((ThiSinhKhoiD) ts).tinhDiem() > 8){
                    isChecked = true;
                    ++count;
                    Object[] row = new Object[]{
                        ts.getHoTen(), ts.getSoBaoDanh(), ts.getTruongHoc(), ts.getDiemCong(), ((ThiSinhKhoiD) ts).DIEM_SAN, "Khoi D", ((ThiSinhKhoiD) ts).getDiemToan(), 
                        ((ThiSinhKhoiD) ts).getDiemVan(), ((ThiSinhKhoiD) ts).getDiemAnh(), ((ThiSinhKhoiD) ts).tinhDiem()
                    };
                    tableModel.addRow(row);
                }
            }
        }
        tableModel.fireTableDataChanged();
        if(isChecked == false){
            JOptionPane.showMessageDialog(rootPane, "Khong Co Thi Sinh Nao Tren 8 Diem!");
        }
        if(count != 0){
            JOptionPane.showMessageDialog(rootPane, "Co " + count + " Thi Sinh Tren 8 Diem!");
        }
    }//GEN-LAST:event_btnCoDiemTren8ActionPerformed

    private void btnThapHonDiemSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThapHonDiemSanActionPerformed
        // TODO add your handling code here:
        xoaDuLieuCu();
        
        boolean isChecked = false;
        int count = 0;
        
        for(ThiSinh ts : danhSachThiSinh){
            if(ts instanceof ThiSinhKhoiA){
                if(((ThiSinhKhoiA) ts).tinhDiem() < 3){
                    isChecked = true;
                    ++count;
                    Object[] row = new Object[]{
                        ts.getHoTen(), ts.getSoBaoDanh(), ts.getTruongHoc(), ts.getDiemCong(), ((ThiSinhKhoiA) ts).DIEM_SAN, "Khoi A", ((ThiSinhKhoiA) ts).getDiemToan(), 
                        ((ThiSinhKhoiA) ts).getDiemLy(), ((ThiSinhKhoiA) ts).getDiemHoa(), ((ThiSinhKhoiA) ts).tinhDiem()
                    };
                    tableModel.addRow(row);
                }
            }
            else if(ts instanceof ThiSinhKhoiD){
                if(((ThiSinhKhoiD) ts).tinhDiem() < 3){
                    isChecked = true;
                    ++count;
                    Object[] row = new Object[]{
                        ts.getHoTen(), ts.getSoBaoDanh(), ts.getTruongHoc(), ts.getDiemCong(), ((ThiSinhKhoiD) ts).DIEM_SAN, "Khoi D", ((ThiSinhKhoiD) ts).getDiemToan(), 
                        ((ThiSinhKhoiD) ts).getDiemVan(), ((ThiSinhKhoiD) ts).getDiemAnh(), ((ThiSinhKhoiD) ts).tinhDiem()
                    };
                    tableModel.addRow(row);
                }
            }
        }
        tableModel.fireTableDataChanged();
        if(isChecked == false){
            JOptionPane.showMessageDialog(rootPane, "Khong Co Thi Sinh Nao Thap Hon Diem San!");
        }
        if(count != 0){
            JOptionPane.showMessageDialog(rootPane, "Co " + count + " Thi Sinh Thap Hon Diem San!");
        }
    }//GEN-LAST:event_btnThapHonDiemSanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMoiThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMoiThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMoiThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMoiThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMoiThiSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoDiemTren8;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnThapHonDiemSan;
    private javax.swing.JButton btnThiSinhKhoiA;
    private javax.swing.JButton btnThiSinhKhoiD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbKhoiA;
    private javax.swing.JRadioButton rbKhoiD;
    private javax.swing.JTable tableThiSinh;
    private javax.swing.JTextField txtDiemAnhD;
    private javax.swing.JTextField txtDiemCong;
    private javax.swing.JTextField txtDiemHoaA;
    private javax.swing.JTextField txtDiemLyA;
    private javax.swing.JTextField txtDiemSan;
    private javax.swing.JTextField txtDiemToanA;
    private javax.swing.JTextField txtDiemToanD;
    private javax.swing.JTextField txtDiemVanD;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoBaoDanh;
    private javax.swing.JTextField txtTruongHoc;
    // End of variables declaration//GEN-END:variables
}
