/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package De3_2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author An Nguyen Van
 */
public class ThemRuong extends javax.swing.JFrame {

    /**
     * Creates new form ThemRuong
     */
    
    private ArrayList<Ruong> danhSachRuong;
    private ArrayList<RuongVuong> danhSachRuongVuong;
    private ArrayList<RuongChuNhat> danhSachRuongChuNhat;
    private DefaultTableModel tableModel;
    private ButtonGroup bg;
    
    public ThemRuong() {
        initComponents();
        setLocationRelativeTo(null);
        danhSachRuong = new ArrayList<>();
        danhSachRuongVuong = new ArrayList<>();
        danhSachRuongChuNhat = new ArrayList<>();
        
        tableModel = (DefaultTableModel) tblRuong.getModel();
        
        bg = new ButtonGroup();
        bg.add(RuongVuong);
        bg.add(RuongChuNhat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaRuong = new javax.swing.JTextField();
        txtTenChuHo = new javax.swing.JTextField();
        txtLoaiCayTrong = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtDoDai = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();
        btnThongKeRuongVuong = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RuongVuong = new javax.swing.JRadioButton();
        RuongChuNhat = new javax.swing.JRadioButton();
        txtChieuDai = new javax.swing.JTextField();
        btnDong = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnThongKeRuongChuNhat = new javax.swing.JButton();
        btnThongKeLoaiCayTrong = new javax.swing.JButton();
        BtnThongKeRuongViPham = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRuong = new javax.swing.JTable();
        txtChieuRong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma Ruong:");

        jLabel2.setText("Ten Chu Ho:");

        jLabel3.setText("Loai Cay Trong:");

        jLabel4.setText("Dien Tich Toi Da:");

        jLabel5.setText("Do Dai:");

        jTextField4.setEditable(false);
        jTextField4.setText("100");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnLuuFile.setText("Luu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        btnThongKeRuongVuong.setText("Thong Ke Ruong Vuong");
        btnThongKeRuongVuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeRuongVuongActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THEM RUONG");

        jLabel7.setText("Loai Ruong");

        RuongVuong.setText("RuongVuong");
        RuongVuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuongVuongActionPerformed(evt);
            }
        });

        RuongChuNhat.setText("RuongChuNhat");
        RuongChuNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuongChuNhatActionPerformed(evt);
            }
        });

        txtChieuDai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChieuDaiActionPerformed(evt);
            }
        });

        btnDong.setText("Dong");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THONG KE");

        btnThongKeRuongChuNhat.setText("Thong Ke Ruong Chu Nhat");
        btnThongKeRuongChuNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeRuongChuNhatActionPerformed(evt);
            }
        });

        btnThongKeLoaiCayTrong.setText("Loai Cay Trong Nhieu Nhat");
        btnThongKeLoaiCayTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeLoaiCayTrongActionPerformed(evt);
            }
        });

        BtnThongKeRuongViPham.setText("Ruong Vi Pham Dien Tich");
        BtnThongKeRuongViPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThongKeRuongViPhamActionPerformed(evt);
            }
        });

        tblRuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma Ruong", "Ten Chu Ho", "Loai Cay Trong", "Dien Tich Toi Da", "Do Dai", "Dien Tich"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRuong);

        jLabel9.setText("Chieu Dai");

        jLabel10.setText("Chieu Rong");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtMaRuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDoDai, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RuongVuong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLuu))
                            .addComponent(txtLoaiCayTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnLuuFile)
                        .addGap(37, 37, 37)
                        .addComponent(btnDong))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtChieuDai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtChieuRong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(RuongChuNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThongKeRuongVuong)
                                .addGap(32, 32, 32)
                                .addComponent(btnThongKeRuongChuNhat)
                                .addGap(26, 26, 26)
                                .addComponent(btnThongKeLoaiCayTrong)
                                .addGap(27, 27, 27)
                                .addComponent(BtnThongKeRuongViPham)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaRuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(RuongVuong)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RuongChuNhat)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDoDai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtChieuDai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLoaiCayTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtChieuRong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu)
                    .addComponent(btnLuuFile)
                    .addComponent(btnDong))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThongKeRuongVuong)
                    .addComponent(btnThongKeRuongChuNhat)
                    .addComponent(btnThongKeLoaiCayTrong)
                    .addComponent(BtnThongKeRuongViPham))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void resetForm(){
        txtMaRuong.setText("");
        txtTenChuHo.setText("");
        txtLoaiCayTrong.setText("");
        txtDoDai.setText("");
        txtChieuDai.setText("");
        txtChieuRong.setText("");
        bg.clearSelection();
    }
    
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(RuongVuong.isSelected()){
            RuongVuong rv = new RuongVuong();
            
            rv.setMaRuong(txtMaRuong.getText());
            rv.setTenChuHo(txtTenChuHo.getText());
            rv.setLoaiCayTrong(txtLoaiCayTrong.getText());
            rv.setDoDaiCanh(Double.parseDouble(txtDoDai.getText()));
            
            danhSachRuongVuong.add(rv);
            danhSachRuong.add(rv);
            JOptionPane.showMessageDialog(rootPane, "Them Ruong Vuong Thanh Cong!");
        }
        else if(RuongChuNhat.isSelected()){
            RuongChuNhat rcn = new RuongChuNhat();
            
            rcn.setMaRuong(txtMaRuong.getText());
            rcn.setTenChuHo(txtTenChuHo.getText());
            rcn.setLoaiCayTrong(txtLoaiCayTrong.getText());
            rcn.setChieuDai(Double.parseDouble(txtChieuDai.getText()));
            rcn.setChieuRong(Double.parseDouble(txtChieuRong.getText()));
            
            danhSachRuongChuNhat.add(rcn);
            danhSachRuong.add(rcn);
            JOptionPane.showMessageDialog(rootPane, "Them Ruong Chu Nhat Thanh Cong!");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Loi khi nhap du lieu! Vui long thu lai");
        }
        resetForm();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        try {
            File file = new File("ruongDe3_2.txt");
            PrintWriter pw = new PrintWriter(file);
            
            for(Ruong ruong : danhSachRuong){
                pw.println(ruong);
            }
            
            pw.close();
            JOptionPane.showMessageDialog(rootPane, "Ghi File Thanh Cong! Vui Long Kiem Tra file ruongDe3_2.txt" + file.getPath());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ThemRuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuFileActionPerformed

    private void btnThongKeRuongVuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeRuongVuongActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < tableModel.getRowCount(); i++){
            tableModel.removeRow(i);
        }
        
        for(RuongVuong rv : danhSachRuongVuong){
            Object[] row = new Object[]{
              rv.getMaRuong(), rv.getTenChuHo(), rv.getLoaiCayTrong(), rv.DIEN_TICH_MAX, rv.getDoDaiCanh(), rv.tinhDienTich()
            };
            tableModel.addRow(row);
            tableModel.fireTableDataChanged();
        }
        
    }//GEN-LAST:event_btnThongKeRuongVuongActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void txtChieuDaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChieuDaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChieuDaiActionPerformed

    private void RuongVuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuongVuongActionPerformed
        // TODO add your handling code here:
        txtChieuDai.setEditable(false);
        txtChieuRong.setEditable(false);
        txtDoDai.setEditable(true);
    }//GEN-LAST:event_RuongVuongActionPerformed

    private void RuongChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuongChuNhatActionPerformed
        // TODO add your handling code here:
        txtChieuDai.setEditable(true);
        txtChieuRong.setEditable(true);
        txtDoDai.setEditable(false);
    }//GEN-LAST:event_RuongChuNhatActionPerformed

    private void btnThongKeRuongChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeRuongChuNhatActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < tableModel.getRowCount(); i++){
            tableModel.removeRow(i);
        }
        
        for(RuongChuNhat rcn : danhSachRuongChuNhat){
            Object[] row = new Object[]{
              rcn.getMaRuong(), rcn.getTenChuHo(), rcn.getLoaiCayTrong(), rcn.DIEN_TICH_MAX, rcn.getChieuDai() + "x" + rcn.getChieuRong(), rcn.tinhDienTich()
            };
            tableModel.addRow(row);
            tableModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnThongKeRuongChuNhatActionPerformed

    private void btnThongKeLoaiCayTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeLoaiCayTrongActionPerformed
        // TODO add your handling code here:
        HashMap<String, Integer> thongKe = new HashMap<>();
        
        for(Ruong r : danhSachRuong){
            thongKe.put(r.getLoaiCayTrong(), thongKe.getOrDefault(r.getLoaiCayTrong(), 0) + 1);
        }
        String loaiPhoBienNhat = null;
        int maxCount = 0;
        for(HashMap.Entry<String, Integer> entry : thongKe.entrySet()){
            if(entry.getValue() > maxCount){
                maxCount = entry.getValue();
                loaiPhoBienNhat = entry.getKey();
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Loai Cay Trong Pho Bien Nhat la: " + loaiPhoBienNhat);
    }//GEN-LAST:event_btnThongKeLoaiCayTrongActionPerformed

    private void BtnThongKeRuongViPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThongKeRuongViPhamActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < tableModel.getRowCount(); i++){
            tableModel.removeRow(i);
        }
        
        for(RuongVuong rv : danhSachRuongVuong){
            if(rv.tinhDienTich() > rv.DIEN_TICH_MAX){
                Object[] row = new Object[]{
                rv.getMaRuong(), rv.getTenChuHo(), rv.getLoaiCayTrong(), rv.DIEN_TICH_MAX, rv.getDoDaiCanh(), rv.tinhDienTich()
            };
            tableModel.addRow(row);
            }
        }
        for(RuongChuNhat rcn : danhSachRuongChuNhat){
            if(rcn.tinhDienTich() > rcn.DIEN_TICH_MAX){
                Object[] row = new Object[]{
                rcn.getMaRuong(), rcn.getTenChuHo(), rcn.getLoaiCayTrong(), rcn.DIEN_TICH_MAX, rcn.getChieuDai() + "x" + rcn.getChieuRong(), rcn.tinhDienTich()
            };
            tableModel.addRow(row);
            }
        }
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_BtnThongKeRuongViPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemRuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemRuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemRuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemRuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemRuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnThongKeRuongViPham;
    private javax.swing.JRadioButton RuongChuNhat;
    private javax.swing.JRadioButton RuongVuong;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnThongKeLoaiCayTrong;
    private javax.swing.JButton btnThongKeRuongChuNhat;
    private javax.swing.JButton btnThongKeRuongVuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblRuong;
    private javax.swing.JTextField txtChieuDai;
    private javax.swing.JTextField txtChieuRong;
    private javax.swing.JTextField txtDoDai;
    private javax.swing.JTextField txtLoaiCayTrong;
    private javax.swing.JTextField txtMaRuong;
    private javax.swing.JTextField txtTenChuHo;
    // End of variables declaration//GEN-END:variables
}
